# Generated by Django 5.0.7 on 2024-09-15 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='logs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='logs.logfile')),
            ],
        ),
        migrations.CreateModel(
            name='LogSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_entries', models.IntegerField(default=0)),
                ('debug_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(blank=True, null=True)),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='logs.logfile')),
            ],
            options={
                'unique_together': {('log_file', 'date')},
            },
        ),
    ]
